### ISSUE TITLE
Propor abordagem para o EJ suportar temas/identidades visuais distintas

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#1]
Aqui vai uma pesquisa sobre qual a melhor maneira de trabalhar com esse tipo de generalização no Angular e como isso se relaciona com o backend Django

**Comment by lucashm** [comment]
Oi! Uma pequena dúvida... Qual o nível de “shift” que é proposto nessa mudança de tema? Seria algo somente visual ou algumas funcionalidades ficariam hidden ou disponíveis a depender do tema?

**Comment by ricardopoppi** [comment]
Opa @lucasssm num primeiro momento manteria a mesma arquitetura e funcionalidades em qq tema

**Comment by luanguimaraesla** [comment]
Testando integração com https://chat.empurrandojuntos.org

**Comment by caiosba** [comment]
Ver https://github.com/ejplatform/ej-front/issues/2
