### ISSUE TITLE
Indicar os ajustes mais pontuais de usabilidade para a equipe de front trabalhar antes dos wireframes ficarem prontos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#13]
Documentos pra basear a análise:

1. https://docs.google.com/document/d/1987u-F-0hiekEMDOHrJt0aLe8pNma_hZHgdv5N-4TZk/edit?ts=5aac4ebc  
2. https://docs.google.com/document/d/13-g0Iig_9aATECCX7REe5rspFfWiURCohri4g56k40M/edit?usp=sharing

**Comment by Heloisecs** [comment]
Documento com os problemas que já podem começar a ser resolvidos pelo front @BrunaNayara 
https://docs.google.com/document/d/1QXGaoNw95fSgJ99q5ed7pgMsi5RuiKl92deutQ6nOtQ/edit
