### ISSUE TITLE
wireframes

### ISSUE THREAD

**Issue by parrahenri** [ejplatform/ej-meta#15]
@luizapeixe detalha essa issue, porfa? Senti necessidade de abrir porque ia comentar que a entrega precisa ser dia 29, para o @ricardopoppi e a @Heloisecs irem pessoalmente na Secretaria (cliente) apresentar e aprovar no dia 30.

**Comment by luizapeixe** [comment]
claro @parrahenri ! Meu plano é entregar até o dia 29 um wireframe da HOME, sugerindo uma nova lógica estrutural dos elementos nessa página, de modo a otimizar a compreensão da plataforma e projeto, na intenção de tornar a navegação mais intuitiva e convidativa. Minha estratégia com isso é primeiro aprovar uma lógica estrutural para depois seguir aplicando ela nas outras páginas, evitando retrabalho. Entretanto podemos estudar a possibilidade de desenhar wireframe também de outras telas que vocês considerarem essenciais para a reunião do dia 30. Como está a expectativa de vocês com relação à isso?

**Comment by parrahenri** [comment]
@ricardopoppi que acha? pra mim, ter o wireframe da tela HOME no dia 29 é o suficiente para aprovar com o cliente. Talvez a tela de uma conversa também?

**Comment by ricardopoppi** [comment]
@parrahenri @luizapeixe o ideal seria termos os wireframes das páginas principais ex: landing, home, página de conversa (se for diferente da home). Se a proposta inovar acrescentando alguma página nova, ter uma ideia dela também será importante. Em suma, não deve ser exaustiva (pra evitar retrabalho) mas tudo que for importante para o conceito da proposta teria que estar desenhado. O que acham?

**Comment by luizapeixe** [comment]
meu receio é se terei tempo hábil para desenhar várias telas :/ acho que home e página de conversa são garantidos! porém mais que isso já não sei afirmar com certeza

**Comment by ricardopoppi** [comment]
combinado @luizapeixe ! Vamos por ai :-)

**Comment by luizapeixe** [comment]
Oi pessoal! Conforme combinado, aí vão as primeiras propostas de wireframe para as páginas de HOME e CONVERSAS da edição CPA do EJ

PS.: Lembrando que aqui estamos analisando principalmente a estrutura e arquitetura dos elementos. Não precisamos nos atentar ainda para questões de design ou conteúdos (porém se for possível já começar a pensar nos textos que deverão compor o site, maravilha!)

Segui algumas orientações do [documento de análise de usabilidade](https://docs.google.com/document/d/1QXGaoNw95fSgJ99q5ed7pgMsi5RuiKl92deutQ6nOtQ/edit) e marquei um "(√)" nas soluções que já foram adotadas nesses wireframes

Eis as telas mobile primeiro e na sequencia as telas desktop. Vale destacar que a home possui uma interação que optamos por descartar na versão mobile: a faixa de interação do usuário com a conversa sobre Política de Drogas. Nessa faixa, inclusive, estou com a ideia de possibilitar que o usuário possa mudar a conversa em destaque a partir de um 'slider' no assunto da conversa. Porém é preciso checar com o pessoal da implementação se esta idéia é factível.

# Homepage mobile:

![wf_mobile_cpahomev1](https://user-images.githubusercontent.com/6249788/38115345-089c6a38-3382-11e8-8fd7-45bcf8757191.png)


# Dropdowns do menu mobile:

![dropdown_mobile](https://user-images.githubusercontent.com/6249788/38116045-cc0482ce-3384-11e8-946a-912f01f0c3df.png)


# Página da conversa mobile:

![wf_mobile_cpaconversav1](https://user-images.githubusercontent.com/6249788/38115926-526196aa-3384-11e8-884c-019b7fcda471.png)


# Homepage desktop:

![wf_homev3](https://user-images.githubusercontent.com/6249788/38116171-5de63e94-3385-11e8-80b4-754b0c92fabc.png)


# Página da conversa Desktop:

![wf_conversav2](https://user-images.githubusercontent.com/6249788/38116186-6c4f47f0-3385-11e8-8262-8d890e666cf2.png)


Se quiserem, podemos marcar um call para conversar sobre os layouts na semana que vem. 
Qualquer dúvida, estou por aqui!

**Comment by parrahenri** [comment]
@luizapeixe quando botar no invision me avisa por aqui com o link porfa?

**Comment by luizapeixe** [comment]
aí vai o link pro invision: https://projects.invisionapp.com/d/main#/projects/boards/6029080

**Comment by luizapeixe** [comment]
Oi pessoal!
Estou explorando e entendendo melhor o InVision. 

### Adicionei aos PROTOTYPES as primeiras propostas de telas (Desktop e Mobile) da página de perfil. 

Dêem uma confierida lá ;)
--> [https://invis.io/PKGOLD0N25F](https://invis.io/PKGOLD0N25F)

incluí tb algumas funções de clique, então já é possível acessar as páginas desenvolvidas pelos seus links no menu e botões ao longo dos layouts.

aguardo seus feedbacks! ;*

**Comment by parrahenri** [comment]
Ficou massa demais!

**Comment by ricardopoppi** [comment]
Entrega feita, aprimoramentos estão sendo tratados em issue específica no novo board no ej-server
