### ISSUE TITLE
Desenvolver estudos para customização de layout do rocketchat para o CPA

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#17]
conforme encaminhamento da reunião de briefing sobre o uso do rocket, o time de design/ux fará uma proposta de customizações baseadas nas possibilidades oferecidas pela ferramenta

**Comment by luizapeixe** [comment]
Certo! Algo determinante sobre isso é se vamos adotar pro rocket um visual mais baseado na identidade do CPA ou do EJ, ou um mix dos dois. Pra isso, é importante termos as versões finais aprovadas da(s) identidade(s) que vamos usar como base para customização do Rocket.

**Comment by ricardopoppi** [comment]
Fechando essa issue pois a proposta foi feita. Está em fase de implementação. Agora vamos concentrar as tarefas de customização do rocket no novo board.
