### ISSUE TITLE
Criar metas estratégicas, épicas e histórias de usuário para a primeira entrega

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#18]

**Comment by altjohndev** [comment]
@ricardopoppi @parrahenri posso ajudar vocês, tenho experiência em E.R.

**Comment by ricardopoppi** [comment]
Excelente @arkye vou te puxar pro docs (o método vai ser criar no docs e qdo tivermos uma versão estável transporto pra wiki do repo do mdh

**Comment by altjohndev** [comment]
Fiz dois documentos para ajudar vocês nas definições:

* [Instruções](https://github.com/ejplatform/ej-meta/wiki/Instru%C3%A7%C3%B5es-para-Especifica%C3%A7%C3%A3o-de-Requisitos)
* [Modelo](https://github.com/ejplatform/ej-meta/wiki/Modelo-de-Especifica%C3%A7%C3%A3o-de-Requisitos)

Tais documentos formalizam o pontapé para uma definição de E.R. para o nosso projeto. Sintam-se a vontade para modificar ou sugerir melhorias.

As definições dos requisitos serão extraídas de quais documentos? 

Se possível, poderia anexar nesta issue ou na wiki as principais referências documentais para eu poder ajudar a definir os requisitos?

**Comment by ricardopoppi** [comment]
@arkye esse documento que estamos usando como base, ele reune tudo: https://docs.google.com/document/d/1pyhb9Lq5IXPnaHl_GHrlX2bmpeAP944XptljHmC3I80

**Comment by altjohndev** [comment]
@ricardopoppi @parrahenri o arquivo (Markdown) está disponível neste endereço: [https://github.com/ejplatform/ej-meta/wiki/Especifica%C3%A7%C3%A3o-de-Requisitos-Release-1](https://github.com/ejplatform/ej-meta/wiki/Especifica%C3%A7%C3%A3o-de-Requisitos-Release-1)

**Comment by altjohndev** [comment]
Mapeei todas as histórias que pude estabelecer de acordo com a documentação e as telas

**Comment by ricardopoppi** [comment]
Sensacional @arkye !!! Entre amanhã e sexta eu e @parrahenri revisamos, complementamos algo se precisar e criamos uma seção pra futuros backlogs se tiver alguma que não será entregue na sexta. Tá com a gente a bola agora, valeu demais.

**Comment by parrahenri** [comment]
@arkye parabéns pelo sensacional trabalho!

**Comment by ricardopoppi** [comment]
Feito
