### ISSUE TITLE
Desenvolver proposta da gameficação do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#19]
Além dos diversos subsídios que estão sendo compartilhados, importante considerar o conceito do Empurrando Juntos documentado nesse artigo: https://medium.com/cidades-democr%C3%A1ticas/como-o-empurrando-juntos-vai-funcionar-entenda-os-perfis-que-criamos-40743ee33150

**Comment by ricardopoppi** [comment]
@Heloisecs @luizapeixe @parrahenri @BrunaNayara Sugiro um hangout nosso sobre isso pro briefing inicial

**Comment by parrahenri** [comment]
Sugeri horários aqui: https://doodle.com/poll/wy7d72cgv52avvz9

**Comment by ricardopoppi** [comment]
Fechando essa issue pra gente concentrar no novo board, na frente de [gamefication]
