### ISSUE TITLE
Desenvolver a identidade visual genérica do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#2]
Documento com o briefing https://docs.google.com/document/d/1ZgIQVCt2BcSN4o4Z0td6fnWDNUkoUtxZTKDQewESxAo/edit

**Comment by ricardopoppi** [comment]
@Heloisecs li o briefing, reflete muito bem o que discutimos, ótimo trabalho!

**Comment by Heloisecs** [comment]
- [x] Criar repositório para a criação colaborativa com a @luizapeixe no Resilio Sync (13/03)
- [x] Análise de redes similares ou referências (20/03)

> - [ ] Arquivo de Análise de "similares"
- [x]  Análise de usabilidade Brasil  (19/03)

> - [ ] Arquivo de Análise de usabilidade (formato: Problema + Possíveis soluções)

**Comment by Heloisecs** [comment]
Fase de geração de alternativas

**Comment by Heloisecs** [comment]
- [x] Pesquisa visual com geração de alternativas para um símbolo

- [ ] Paleta de cores derivando do símbolo

- [ ] Pesquisa tipográfica (pesquisar as fontes que farão parte de nossa identidade, aplicadas à interface para textos e títulos, devendo ser condizentes com o objetivo estabelecido pelo briefing).

- [ ] Criação de elementos gráficos auxiliares para a marca (possibilidades: padronagens, mascote, ícones, etc.)

**Comment by ricardopoppi** [comment]
Primeira versão da Idv criada. Novas tarefas relacionadas a isso devem ser abertas no novo board. Fechando essa issue. (cc @Heloisecs )
[MIV_ej.pdf](https://github.com/ejplatform/ej-meta/files/2023778/MIV_ej.pdf)
