### ISSUE TITLE
Proposta de nomenclatura unificada

### ISSUE THREAD

**Issue by Heloisecs** [ejplatform/ej-meta#20]
Criar documento de unificação dos nomes de seções.

**Comment by luizapeixe** [comment]
Aqui vai uma primeira proposta de padronização de nomenclatura das áreas e sessões pro EJ do CPA:

[Proposta de unificação de nomeclaturas](https://docs.google.com/document/d/1mvHF_o22SdjZj1XaYWWfGr1iDzWbUthzetrcX1UzXeE/edit?usp=sharing)

**Comment by ricardopoppi** [comment]
Fechando essa issue. Se for necessário fazer aprimoramentos na nomenclatura sugiro abrir nova issue no novo board.
