### ISSUE TITLE
Criar um mapa de processos e um mapa de interação/fluxo da informação

### ISSUE THREAD

**Issue by Heloisecs** [ejplatform/ej-meta#21]
Existem várias formas de se mapear um sistema. O mapa de processo é uma ferramenta usada no design de serviço e no design de interação que ajuda a visualizar em **ações** o que é necessário para que o usuário interaja de maneira eficiente (geralmente essa etapa, em metodologia, é um passo anterior à criação de telas), a partir desse mapa é muito mais fácil organizar informações e localização de cada elemento, um próximo passo possível é um mapa de interação que já mostra o fluxo de navegação, exemplos abaixo. 

Essas ferramentas são muito úteis para enxergar o projeto como um todo e facilita tomadas de decisão com relação à interface

Mapa de Processo:
![image](https://user-images.githubusercontent.com/9471715/39759879-3a71f266-52aa-11e8-9a45-cc6e092d9ddd.png)
Mapa de interação / Fluxo da informação
![image](https://user-images.githubusercontent.com/9471715/39759931-5a8677c0-52aa-11e8-8f05-908afcd8109f.png)

**Comment by Heloisecs** [comment]
@fabiommendes @BrunaNayara

**Comment by ricardopoppi** [comment]
Mapa criado em ferramenta online: https://realtimeboard.com/app/board/o9J_kz_Lihw=/ (cc @Heloisecs @luizapeixe @fabiommendes )
