### ISSUE TITLE
Desenvolver identidade visual da Plataforma de Participação de Adolescentes (CONANDA)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#3]
Documento para reunião de briefing: https://docs.google.com/document/d/1PkS6dK7ZlQOPp-aCJP6zC7JzZvxBUtz8cDje3F3U_nA/edit?usp=sharing

**Comment by Heloisecs** [comment]
- [x] 26/07 Pesquisa de Referência visual (para orientar cliente)

**Comment by Heloisecs** [comment]
Pesquisa de Referência visual (para orientar cliente): 
Da página 1 à 6 são inspirações de fato e a página 7 são marcas atuais relacionadas a crianças e adolescentes e/ou mobilização social (com elas podemos ver que recursos são mais usados -cores, estilos - e o que fazer e o que não fazer, o que comunica e o que não comunica).
[referencias.pdf](https://github.com/ejplatform/ej-meta/files/1837657/referencias.pdf)

Acho que para alinhamento com o cliente, da 1 à 6 são suficientes; A página 7 é para explicar ao cliente que não estamos saindo do nada, existe um mínimo mapeamento / caminho das pedras. 

@ricardopoppi @parrahenri @luizapeixe

**Comment by ricardopoppi** [comment]
Subsídios feitos. Idv será desenvolvida a partir da aprovação da idv cpa criada pela flacso. Essa tarefa já está refletida no novo board, portanto estou fechando essa issue
