### ISSUE TITLE
Desenvolver diagnóstico do estado atual da usabilidade da participação nas conversas do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-meta#5]

**Comment by ricardopoppi** [comment]
@Heloisecs apresentaria uma preliminar dessa análise na próxima segunda dia 19/março

**Comment by luizapeixe** [comment]
eis os docs de análise de usabilidade que iremos debater na reunião de hoje:
1. https://docs.google.com/document/d/1987u-F-0hiekEMDOHrJt0aLe8pNma_hZHgdv5N-4TZk/edit?ts=5aac4ebc
2. https://docs.google.com/document/d/13-g0Iig_9aATECCX7REe5rspFfWiURCohri4g56k40M/edit?usp=sharing
